version: '3'
services:
    nginx:
      restart: always
      container_name: nginx
      image: nginx:alpine
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./:/app
      ports:
        - 3001:80

    php:
      restart: always
      container_name: php
      image: kraicklist-lumen_php:latest
      volumes:
        - ./:/app
        - ./php.ini:/usr/local/etc/php/php.ini
      expose:
        - 9000

    meilisearch:
      restart: always
      container_name: meilisearch
      image: getmeili/meilisearch:latest
      command: ./meilisearch --master-key=eea8919a-6975-48de-bf5f-1930b4fd9fa8
      volumes:
        - $(pwd)/data.ms:/data.ms
      ports:
        - 7700:7700
      environment:
        - MEILI_ENV=production
        
networks:
  default:
    external:
      name: kraicklist_default