version: '3'
services:
    nginx:
      restart: always
      container_name: nginx
      image: nginx:alpine
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./:/app
      ports:
        - 3001:80

    php:
      restart: always
      container_name: php
      build: .
      volumes:
        - ./:/app
        - ./php.ini:/usr/local/etc/php/php.ini
      expose:
        - 9000
    
        
networks:
  default:
    external:
      name: kraicklist_default